services:
  ros:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    container_name: ros-carla
    privileged: true
    stdin_open: true
    tty: true
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/root/.Xauthority

    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/root/.Xauthority
      - /opt/carla/v0.9.13:/opt/carla
      - ./config:/app/config
      - ./figures:/app/figures
      - ./src:/app/src
      - ./scenario_runner-0.9.13:/app/scenario_runner-0.9.13
      - ./source_env.sh:/app/source_env.sh
      - ./frames.gv:/app/frames.gv

    command: /bin/bash
