/*
 * Copyright (C) 2018-2020 by SenseTime Group Limited. All rights reserved.
 * shenzijian <shenzijian@senseauto.com>
 */
#pragma once
#ifndef CTA_PAR_H
#define CTA_PAR_H
#ifdef __cplusplus
extern "C" {
#endif

#define CTA_MAX_NUM_OBJECTS 100u   // the object's number of side radar output
#define FCTA_MAX_NUM_OBJECTS 100u  // the object's number of side radar output
#define RCTA_MAX_NUM_OBJECTS 100u  // the object's number of side radar output
#define CTA_FCTA_CFG_NUM_OF_WARN_LEVELS 3u
#define CTA_RCTA_CFG_NUM_OF_WARN_LEVELS 3u
#define CTA_ROAD_TYPE_UNKNOWN 0u

#define CTA_EM_GEN_OBJECT_MT_STATE_DELETED \
    0u  // the maintenance state of the current object is deleted
// #define CTA_EM_GEN_OBJECT_MT_STATE_NEW 1u//the maintenance state of the
// current object is new
#define CTA_EM_GEN_OBJECT_MT_STATE_MEASURED \
    2u  // the maintenance state of the current object is measured
// #define CTA_EM_GEN_OBJECT_MT_STATE_PREDICTED 3u//the maintenance state of the
// current object is predicted #define CTA_EM_GEN_OBJECT_MT_STATE_INACTIVE
// 4u//the maintenance state of the current object is inactive #define
// CTA_EM_GEN_OBJECT_MT_STATE_MAX_DIFF_TYPES 5u
#define CTA_OBJ_ROTATED_MIN_LENGTH 0.5f
#define CTA_OBJ_ROTATED_MAX_LENGTH 5.f
#define CTA_OBJ_ROTATED_MIN_WIDTH 0.5f
#define CTA_OBJ_ROTATED_MAX_WIDTH 2.55f
#define CTA_UPDATERATE_FILTER_UP 0.05f
#define CTA_UPDATERATE_FILTER_DOWN 0.025f
#define CTA_ASSOCPROB_FILTER_UP 0.05f
#define CTA_ASSOCPROB_FILTER_DOWN 0.05f
#define CTA_MIN_UPDATERATE_TTC_ACCEL 0.75f
#define CTA_EM_GEN_OBJECT_DYN_PROPERTY_MOVING 0u
// #define CTA_EM_GEN_OBJECT_DYN_PROPERTY_STATIONARY 1u
// #define CTA_EM_GEN_OBJECT_DYN_PROPERTY_ONCOMING 2u
// #define CTA_EM_GEN_OBJECT_DYN_PROPERTY_CROSSING_LEFT 3u
// #define CTA_EM_GEN_OBJECT_DYN_PROPERTY_CROSSING_RIGHT 4u
// #define CTA_EM_GEN_OBJECT_DYN_PROPERTY_UNKNOWN 5u
// #define CTA_EM_GEN_OBJECT_DYN_PROPERTY_MAX_DIFF_TYPES 6u
#define CTA_CT_LPF_DIST2CROSS_FILTER 0.01f
#define CTA_CT_XBREAKTHROUGH_MIN_FILTER 10.f
#define CTA_CT_LARGE_TTC 30.f
#define CTA_CT_TTCFILTER_MAX_DIST2CROS 15.f
#define CTA_CT_TTCFILTER_DOWN_MIN_ALPHA 0.1f
#define CTA_CT_TTCFILTER_DOWN_MAX_ALPHA 0.3f
#define CTA_CT_TTCFILTER_UP_MIN_ALPHA 0.05f
#define CTA_CT_TTCFILTER_UP_MAX_ALPHA 0.2f
#define CTA_CT_REAROBJPROB_DISTX_THRESH 10.f
#define CTA_FCTA_REARTRACK_DEC_PROB 0.02f
#define CTA_FCTA_REARTRACK_IMPLAUSIBLE_THRESH 0.05f
#define CTA_CT_LI_REARPROB_MIN_FIRSTY 25.f
#define CTA_CT_LI_REARPROB_MAX_FIRSTY 40.f
#define CTA_CT_LI_REARPROB_MAX_LIFECYCLE 75.f
#define CTA_CT_LI_REARPROB_MIN_LIFECYCLE 50.f
#define CTA_FCTA_REARTRACK_INC_PROB 0.1f
#define CTA_CT_LI_MAXREARPROB_MAX_DISTY 5.f
#define CTA_CT_MULTIOBJ_SAFE_MARGIN 0.7f
#define CTA_CT_FRONTOBJ_MIN_XYDIFF 2.f
#define CTA_CT_FRONTOBJ_MAX_XYDIFF 10.f
#define CTA_CT_LI_FRONTOBJ_MIN_VXYDIFF 1.f
#define CTA_CT_LI_FRONTOBJ_MAX_VXYDIFF 15.f
// #define CTA_EM_GEN_OBJECT_CLASS_POINT 0u
// #define CTA_EM_GEN_OBJECT_CLASS_CAR 1u
// #define CTA_EM_GEN_OBJECT_CLASS_TRUCK 2u
// #define CTA_EM_GEN_OBJECT_CLASS_PEDESTRAIN 3u
// #define CTA_EM_GEN_OBJECT_CLASS_MOTORCYCLE 4u
// #define CTA_EM_GEN_OBJECT_CLASS_BICYCLE 5u
// #define CTA_EM_GEN_OBJECT_CLASS_WIDE 6u
// #define CTA_EM_GEN_OBJECT_CLASS_MIRROR 7u
#define CTA_EM_GEN_OBJECT_CLASS_MULTIPLE 8u
#define CTA_LPF_VRELXY_ALPHA 0.1f
#define CTA_CT_MAXLATERALRANGE_MIN_EGOSPEED 0.5f
#define CTA_CT_MAXLATRANGE_MAX_VRELX -1.f
#define CTA_CT_MAXLATRANGE_MAX_DISTX 15.f
#define CTA_CT_MAXLATRANGE_MIN_YDIST 1.5f
#define CTA_CT_MAXLATRANGE_MAX_YDIST 2.5f
#define CTA_CT_MAXLATRANGE_MIN_POE 0.99f

// FCTA
#define CTA_FCTA_REARTRACK_ACTIVATION_THRESH 0.9f
#define CTA_FCTA_REARTRACK_DEACTIVATION_THRESH 0.7f
#define CTA_FCTA_REARTRACK_INIT_PROB 0.3f
#define CTA_FCTA_ADAPT_BREAKTHROUGH_MIN_SPEED 0.5f
#define CTA_FCTA_LI_ADAPT_BRK_MIN_CURVE 10.f
#define CTA_FCTA_LI_ADAPT_BRK_MAX_CURVE 50.f
#define CTA_FCTA_LI_ADAPT_BRK_MIN 1.f
#define CTA_FCTA_LI_ADAPT_BRK_MAX 0.f
#define CTA_FCTA_X_BREAKTHROUGH_FILTER 0.05f
#define CTA_FCTA_APPROACH_ANGLE_MARGIN 10.f
#define CTA_FCTA_UPDRATE_MIN 0.8f
#define FCTA_MIRROR_ACTIVATION_THRESH 0.8f
#define FCTA_MIRROR_DEACTIVATION_THRESH 0.5f
#define FCTA_POE_HYST 0.02f;
#define FCTA_UPDRTE_HYST 0.1f;
#define FCTA_ASSOCP_HYST 0.1f;
#define CTA_FCTA_LI_REDEGO_MIN_EGOSPEED 0.f
#define CTA_FCTA_LI_REDEGO_MAX_EGOSPEED 3.f
#define CTA_FCTA_LI_REDEGO_MIN_FACTOR 0.9f
#define CTA_FCTA_LI_REDEGO_MAX_FACTOR 1.f
#define FCTA_LI_POE_MIN_SPEED 30.0f * TUE_C_MS_KMH
#define FCTA_LI_POE_MAX_SPEED 60.0f * TUE_C_MS_KMH
#define FCTA_LI_POE_MIN_POE 0.99f
#define FCTA_LI_POE_MAX_POE 0.93f
#define FCTA_LI_POE_LFT_MIN_LIFETIME 15.f
#define FCTA_LI_POE_LFT_MAX_LIFETIME 25.f
#define FCTA_LI_POE_LFT_MIN_POE 0.93f
#define FCTA_LI_POE_LFT_MAX_POE 0.99f
#define FCTA_LI_UPDATE_MIN_SPEED 30.0f * TUE_C_MS_KMH
#define FCTA_LI_UPDATE_MAX_SPEED 60.0f * TUE_C_MS_KMH
#define FCTA_LI_UPDATE_MIN_POE 0.85f
#define FCTA_LI_UPDATE_MAX_POE 0.75f
#define FCTA_LI_UPDATE_LFT_MIN_LIFETIME 15.f
#define FCTA_LI_UPDATE_LFT_MAX_LIFETIME 25.f
#define FCTA_LI_UPDATE_LFT_MIN_UPDATE 0.75f
#define FCTA_LI_UPDATE_LFT_MAX_UPDATE 0.85f
#define FCTA_LI_ASSOCP_MIN_SPEED 10.0f * TUE_C_MS_KMH
#define FCTA_LI_ASSOCP_MAX_SPEED 50.0f * TUE_C_MS_KMH
#define FCTA_LI_ASSOCP_MIN_ASSOCP 0.8f
#define FCTA_LI_ASSOCP_MAX_ASSOCP 0.3f
#define FCTA_LI_ASSOCP_RNG_MIN_RANGE 40.f
#define FCTA_LI_ASSOCP_RNG_MAX_RANGE 30.f
#define FCTA_LI_ASSOCP_RNG_MIN_ASSOCP 0.4f
#define FCTA_LI_ASSOCP_RNG_MAX_ASSOCP 1.f
#define FCTA_BREAKTHROUGH_HYSTERESIS 2.f
#define FCTA_BREAKTHROUGH_MIN_SPEED 2.78f  // 0.5f
#define FCTA_BREAKTHROUGH_MAX_CURVE 0.5f
#define FCTA_CONFI_UPDATE_MAX 20.f
#define FCTA_CONFI_UPDATE_MIN 5.f
#define FCTA_CONFI_UPDATE_MAX_EFOV 10.f
#define FCTA_CONFI_UPDATE_MIN_EFOV 2.f
#define FCTA_TTC_EFOV_THRESH 1.f
#define FCTA_MAX_Y_GEN_RELEVENCE 5.f
#define FCTA_SHORT_WARNING_THRESH 0.1f
#define FCTA_SHORT_WARN_DIST_THRESH 1.0f
#define FCTA_SHORTWARN_CLOSEOBJ_TTC_THR 0.25f
#define FCTA_APPROACH_ANGLE_HYST 10.f
#define FCTA_OBJ_VALID_DISTY_MAX 5.f
#define FCTA_OBJ_VALID_ARELX_MAX 3.5f
#define FCTA_OBJ_VALID_ARELY_MAX 3.5f
#define FCTA_OBJ_VALID_VRELY_MIN -2.f
#define FCTA_OBJ_VALID_VRELY_MAX 0.5f
#define FCTA_OBJ_VALID_VABS_MAX 3.f
#define FCTA_VX_DIFF_MOV_INVALID 1.f
#define FCTA_VX_DIFF_MOV_VALID 0.5f
#define FCTA_OBJ_VALID_DISTY_TRSH 1.5f
#define FCTA_REL_MAX_FIRSTX 5.f
#define FCTA_REL_MIN_FIRSTX -10.f
#define FCTA_REL_MAX_LAT_SEN_RANGE 25.f
#define FCTA_VEGO_THRESH_STAT2MOV 0.1f
#define FCTA_LI_MOVTRSH_MIN_DISTY 5.f
#define FCTA_LI_MOVTRSH_MAX_DISTY 20.f
#define FCTA_LI_MOVTRSH_MIN_THRESH 8.f
#define FCTA_LI_MOVTRSH_MAX_THRESH 5.f
#define FCTA_LI_MOVTRSH_MIN_SPD 0.f
#define FCTA_LI_MOVTRSH_MAX_SPD 3.f
#define FCTA_LI_MOVTRSH_MIN_MOVTRSH 2.f
#define FCTA_LI_MOVTRSH_MAX_MOVTRSH 4.f
#define FCTA_SPDOVERGND_RELEVANT_FACTOR 0.5f
#define FCTA_MAX_Y_GEN_RELEVANCE 5.f
#define FCTA_REL_LIFECYCLE_MIN 100u
#define FCTA_REL_VRELX_MAX 2.5f
#define FCTA_MIN_LIFECYCLE_RELEVANT 10u
// #define FCTA_HIT_CONFI_THRESH 90u
#define FCTA_RCS_THRESH -20.f
// RCTA
#define RCTA_NUM_OF_WARN_LEVELS \
    3u  // set number of warning parameters which can be calculated. Valid range
        // is 1 to 3
#define RCTA_APPROACH_ANGLE_MARGIN 5.0f  // the margin of RCTA approach angle
#define RCTA_SIDE_APPROACH_FIRSTY_MIN 4.f
#define RCTA_SIDE_APPROACH_DISTY_MIN 8.f
#define RCTA_APPROACH_ANGLE_HYST 10.f
#define RCTA_APPROACH_ANGLE_MAX_STD 25.f
#define RCTA_MIRROR_ACTIVATION_THRESH 0.8f
#define RCTA_MIRROR_DEACTIVATION_THRESH 0.5f
#define RCTA_RELEVANCE_LIFECYCLE_MIN 10u
#define RCTA_LI_POE_MIN_SPEED 30.0f * TUE_C_MS_KMH
#define RCTA_LI_POE_MAX_SPEED 60.0f * TUE_C_MS_KMH
#define RCTA_LI_POE_MIN_POE 0.99f
#define RCTA_LI_POE_MAX_POE 0.93f
#define RCTA_LI_POE_LFT_MIN_LIFETIME 15.f
#define RCTA_LI_POE_LFT_MAX_LIFETIME 25.f
#define RCTA_LI_POE_LFT_MIN_POE 0.93f
#define RCTA_LI_POE_LFT_MAX_POE 0.99f
#define RCTA_LI_UPDATE_MIN_SPEED 30.0f * TUE_C_MS_KMH
#define RCTA_LI_UPDATE_MAX_SPEED 60.0f * TUE_C_MS_KMH
#define RCTA_LI_UPDATE_MIN_POE 0.85f
#define RCTA_LI_UPDATE_MAX_POE 0.75f
#define RCTA_LI_UPDATE_LFT_MIN_LIFETIME 15.f
#define RCTA_LI_UPDATE_LFT_MAX_LIFETIME 25.f
#define RCTA_LI_UPDATE_LFT_MIN_UPDATE 0.75f
#define RCTA_LI_UPDATE_LFT_MAX_UPDATE 0.85f
#define RCTA_LI_ASSOCP_MIN_SPEED 10.0f * TUE_C_MS_KMH
#define RCTA_LI_ASSOCP_MAX_SPEED 50.0f * TUE_C_MS_KMH
#define RCTA_LI_ASSOCP_MIN_ASSOCP 0.8f
#define RCTA_LI_ASSOCP_MAX_ASSOCP 0.3f
#define RCTA_LI_ASSOCP_RNG_MIN_RANGE 40.f
#define RCTA_LI_ASSOCP_RNG_MAX_RANGE 30.f
#define RCTA_LI_ASSOCP_RNG_MIN_ASSOCP 0.4f
#define RCTA_LI_ASSOCP_RNG_MAX_ASSOCP 1.f
#define RCTA_POE_HYST 0.02f;
#define RCTA_UPDRTE_HYST 0.1f;
#define RCTA_ASSOCP_HYST 0.1f;
#define RCTA_BREAKTHROUGH_HYSTERESIS 2.f
#define RCTA_LI_BRKACTIVE_MIN_HITCONF 5.f
#define RCTA_LI_BRKACTIVE_MAX_HITCONF 20.f
// #define RCTA_LI_BRKINACTIVE_MIN_HITCONF -20.f
// #define RCTA_LI_BRKINACTIVE_MAX_HITCONF -5.f
#define RCTA_SHORT_WARNING_THRESH 0.f
// #define RCTA_HIT_CONFI_THRESH 90u
#define RCTA_RCS_THRESH -20.f
#define RCTA_MULTIOBJ_SAFE_MARGIN 0.7f
#define RCTA_MULTIOBJ_INTERRUPT_CYCLES 1u

#define EGO_VEHICLE_GEAR_DEFAULT 0u
#define EGO_VEHICLE_GEAR_PARK 1u
#define EGO_VEHICLE_GEAR_REVERSE 2u
#define EGO_VEHICLE_GEAR_NEUTRAL 3u
#define EGO_VEHICLE_GEAR_DRIVE 4u
#define EGO_VEHICLE_GEAR_INVALID 5u

#ifdef __cplusplus
}
#endif
#endif
