/*
 * Copyright (C) 2018-2020 by SenseTime Group Limited. All rights reserved.
 * wangsifan <wangsifan@senseauto.com>
 */
#ifndef SENSEAUTO_PILOT_DECISION_PILOT_DECISION_SDK_DECISION_SRC_LCF_SEN_ALP_LCF_ALP_PAR_H_
#define SENSEAUTO_PILOT_DECISION_PILOT_DECISION_SDK_DECISION_SRC_LCF_SEN_ALP_LCF_ALP_PAR_H_

#define ALP_EGOLANE_VALID_BITFIED_DEFAULT (0)
#define ALP_EGOLANE_VALID_BITFIED_BRIDGE (8192)
#define ALP_EGOLANE_INVALID_BITFIED_BRIDGE (49151)

#define ALP_ADJLANE_ALIVECOUNTER_VALUE_MIN (0u)
#define ALP_ADJLANE_ALIVECOUNTER_VALUE_MAX (100u)

#define ALP_PROPORT_ALIVECOUNTER_VALUE_DEFALUT (0)
#define ALP_PROPORT_QUALITY_BITFIED_DEFAULT (65535u)

#define ALP_ADJLANE_AVAILABLE_VALUE_DEFAULT (0)
#define ALP_ADJLANE_LATDISTANCE_C0_DEFALUT (15)
#define ALP_ADJLANE_YAWANGLE_C1_DEFAULT (0)
#define ALP_ADJLANE_CURVATURE_C2_DEFAULT (0)
#define ALP_ADJLANE_CURVATURE_RATE_C3_DEFAULT (0)
#define ALP_ADJLANE_VALIDLENGTH_VALUE_DEFAULT (0)
#define ALP_ADJLANE_QUALITY_VALUE_DEFAULT (0)     // E_ABPR_MQ_NO_TLB
#define ALP_ADJLANE_MARKERTYPE_VALUE_DEFAULT (0)  // ABD_MT_NO_LINE

#define ALP_ADJLANE_QUALITY_BITFIED_DEFAULT (0x00)
#define ALP_ADJLANE_AVAILABLE_BITFIED_MASK (0x01)
#define ALP_ADJLANE_STEPDEBOUNCED_BITFIED_MASK (0x02)
#define ALP_ADJLANE_BRIDGING_BITFIED_MASK (0x04)
#define ALP_ADJLANE_STEPONBRIDGING_BITFIED_MASK (0x08)
#endif  // SENSEAUTO_PILOT_DECISION_PILOT_DECISION_SDK_DECISION_SRC_LCF_SEN_ALP_LCF_ALP_PAR_H_
