/* **********************************************************************
Autosar Memory Map
**************************************************************************** */
// #define DLMU2_START_CODE
// #include "Mem_Map.h" /* PRQA S 5087 */ /* MD_MSR_MemMap */
#include "LDPSA_Ext.h"
#include "LDPSA.h"

#define ASW_QM_CORE2_MODULE_START_SEC_VAR_NO_INIT_UNSPECIFIED
#include "ASW_MemMap.h"
real32_T LDPSAI_VehWid_Mi;
real32_T LDPSAI_VehSpdActu_Mps;
real32_T LDPSAI_SpdVelShow_Kmph;
real32_T LDPSAI_VehAccSpdX_Npkg;
real32_T LDPSAI_VehAccSpdY_Npkg;
real32_T LDPSAI_VehCurv_ReMi;
uint8_T LDPSAI_TrnSgl_St;
real32_T LDPSAI_WheSteAgl_Dgr;
real32_T LDPSAI_SteAglSpd_Dgpm;
boolean_T LDPSAI_LDPSwitchEn_B;
uint8_T LDPSAI_LDPMod_St;
boolean_T LDPSAI_LDPErrCdtn_B;
boolean_T LDPSAI_DtctLnChag_B;
real32_T LDPSAI_LnWidCalc_Mi;
real32_T LDPSAI_PstnXLf_Mi;
real32_T LDPSAI_PstnXRi_Mi;
real32_T LDPSAI_PstnYLf_Mi;
real32_T LDPSAI_PstnYSafeLf_Mi;
real32_T LDPSAI_PstnYRi_Mi;
real32_T LDPSAI_PstnYSafeRi_Mi;
real32_T LDPSAI_HeadAglLf_Rad;
real32_T LDPSAI_HeadAglSafeLf_Rad;
real32_T LDPSAI_HeadAglRi_Rad;
real32_T LDPSAI_HeadAglSafeRi_Rad;
real32_T LDPSAI_CurvLf_ReMi;
real32_T LDPSAI_CurvSafeLf_ReMi;
real32_T LDPSAI_CurvRi_ReMi;
real32_T LDPSAI_CurvSafeRi_ReMi;
real32_T LDPSAI_CurvRateLf_ReMi2;
real32_T LDPSAI_CurvRateRi_ReMi2;
real32_T LDPSAI_VldLengLf_Mi;
real32_T LDPSAI_VldLengRi_Mi;
uint8_T LDPSAI_IvldLnSafeLf_St;
uint16_T LDPSAI_LnIVldLf_St;
uint8_T LDPSAI_IvldLnSafeRi_St;
uint16_T LDPSAI_LnIVldRi_St;
uint16_T LDPSAI_VehStIvld_St;
uint8_T LDPSAI_IvldStDrv_St;
uint8_T LDPSAI_CtrlStEn_St;
uint8_T LDPSAI_StError_St;
uint8_T LDPSAI_CtrlStNoAvlb_St;
uint8_T LDPSAI_PrjSpecQu_St;
boolean_T LDPSAI_DtctCstruSite_B;
real32_T LDPSAI_CycleTime_Sec;
real32_T LDPSAI_ABDTimeStamp_Sec;
real32_T LDPSAI_PstnYCent_Mi;
real32_T LDPSAI_VehYawRate_rps;
boolean_T LDPSAI_AEBActive_B;
boolean_T NVRAM_LDPSwitch_B;
real32_T NVRAM_LDPStartupSpd_Kmph;
real32_T LDPSAI_VehStartupSpdHMI_Kmph;
#define ASW_QM_CORE2_MODULE_STOP_SEC_VAR_NO_INIT_UNSPECIFIED
#include "ASW_MemMap.h"

void LCF_LDPSA_Reset(void) {
    LDPSA_initialize();
}

void LCF_LDPSA_Exec(const sLDPSAInput_t* pLDPSAInput,
                    const sLDPSAParam_t* pLDPSAParam,
                    sLDPSAOutput_t* pLDPSAOutput,
                    sLDPSADebug_t* pLDPSADebug) {
    // printf("--------------------LDPSA--------------------\n");
    /**************************************LDPSA
     * input***********************************************************/
    LDPSAI_VehWid_Mi = pLDPSAParam->LDPSAI_VehWid_Mi;

    LDPSAI_VehSpdActu_Mps = pLDPSAInput->LDPSAI_VehSpdActu_Mps;
    LDPSAI_SpdVelShow_Kmph = pLDPSAInput->LDPSAI_SpdVelShow_Kmph;
    LDPSAI_VehAccSpdX_Npkg = pLDPSAInput->LDPSAI_VehAccSpdX_Npkg;
    LDPSAI_VehAccSpdY_Npkg = pLDPSAInput->LDPSAI_VehAccSpdY_Npkg;
    LDPSAI_VehCurv_ReMi = pLDPSAInput->LDPSAI_VehCurv_ReMi;
    LDPSAI_TrnSgl_St = pLDPSAInput->LDPSAI_TrnSgl_St;
    LDPSAI_WheSteAgl_Dgr = pLDPSAInput->LDPSAI_WheSteAgl_Dgr;
    LDPSAI_SteAglSpd_Dgpm = pLDPSAInput->LDPSAI_SteAglSpd_Dgpm;
    LDPSAI_LDPSwitchEn_B = pLDPSAInput->LDPSAI_LDPSwitchEn_B;
    LDPSAI_LDPMod_St = pLDPSAInput->LDPSAI_LDPMod_St;
    LDPSAI_LDPErrCdtn_B = pLDPSAInput->LDPSAI_LDPErrCdtn_B;
    LDPSAI_DtctLnChag_B = pLDPSAInput->LDPSAI_DtctLnChag_B;
    LDPSAI_LnWidCalc_Mi = pLDPSAInput->LDPSAI_LnWidCalc_Mi;
    LDPSAI_PstnXLf_Mi = pLDPSAInput->LDPSAI_PstnXLf_Mi;
    LDPSAI_PstnXRi_Mi = pLDPSAInput->LDPSAI_PstnXRi_Mi;
    LDPSAI_PstnYLf_Mi = pLDPSAInput->LDPSAI_PstnYLf_Mi;
    LDPSAI_PstnYSafeLf_Mi = pLDPSAInput->LDPSAI_PstnYSafeLf_Mi;
    LDPSAI_PstnYRi_Mi = pLDPSAInput->LDPSAI_PstnYRi_Mi;
    LDPSAI_PstnYSafeRi_Mi = pLDPSAInput->LDPSAI_PstnYSafeRi_Mi;
    LDPSAI_HeadAglLf_Rad = pLDPSAInput->LDPSAI_HeadAglLf_Rad;
    LDPSAI_HeadAglSafeLf_Rad = pLDPSAInput->LDPSAI_HeadAglSafeLf_Rad;
    LDPSAI_HeadAglRi_Rad = pLDPSAInput->LDPSAI_HeadAglRi_Rad;
    LDPSAI_HeadAglSafeRi_Rad = pLDPSAInput->LDPSAI_HeadAglSafeRi_Rad;
    LDPSAI_CurvLf_ReMi = pLDPSAInput->LDPSAI_CurvLf_ReMi;
    LDPSAI_CurvSafeLf_ReMi = pLDPSAInput->LDPSAI_CurvSafeLf_ReMi;
    LDPSAI_CurvRi_ReMi = pLDPSAInput->LDPSAI_CurvRi_ReMi;
    LDPSAI_CurvSafeRi_ReMi = pLDPSAInput->LDPSAI_CurvSafeRi_ReMi;
    LDPSAI_CurvRateLf_ReMi2 = pLDPSAInput->LDPSAI_CurvRateLf_ReMi2;
    LDPSAI_CurvRateRi_ReMi2 = pLDPSAInput->LDPSAI_CurvRateRi_ReMi2;
    LDPSAI_VldLengLf_Mi = pLDPSAInput->LDPSAI_VldLengLf_Mi;
    LDPSAI_VldLengRi_Mi = pLDPSAInput->LDPSAI_VldLengRi_Mi;
    LDPSAI_IvldLnSafeLf_St = pLDPSAInput->LDPSAI_IvldLnSafeLf_St;
    LDPSAI_LnIVldLf_St = pLDPSAInput->LDPSAI_LnIVldLf_St;
    LDPSAI_IvldLnSafeRi_St = pLDPSAInput->LDPSAI_IvldLnSafeRi_St;
    LDPSAI_LnIVldRi_St = pLDPSAInput->LDPSAI_LnIVldRi_St;
    LDPSAI_VehStIvld_St = pLDPSAInput->LDPSAI_VehStIvld_St;
    LDPSAI_IvldStDrv_St = pLDPSAInput->LDPSAI_IvldStDrv_St;
    LDPSAI_CtrlStEn_St = pLDPSAInput->LDPSAI_CtrlStEn_St;
    LDPSAI_StError_St = pLDPSAInput->LDPSAI_StError_St;
    LDPSAI_CtrlStNoAvlb_St = pLDPSAInput->LDPSAI_CtrlStNoAvlb_St;
    LDPSAI_PrjSpecQu_St = pLDPSAInput->LDPSAI_PrjSpecQu_St;
    LDPSAI_DtctCstruSite_B = pLDPSAInput->LDPSAI_DtctCstruSite_B;
    LDPSAI_CycleTime_Sec = pLDPSAInput->LDPSAI_CycleTime_Sec;
    LDPSAI_ABDTimeStamp_Sec = pLDPSAInput->LDPSAI_ABDTimeStamp_Sec;
    LDPSAI_PstnYCent_Mi = pLDPSAInput->LDPSAI_PstnYCent_Mi;
    LDPSAI_VehYawRate_rps = pLDPSAInput->LDPSAI_VehYawRate_rps;
    LDPSAI_AEBActive_B = pLDPSAInput->LDPSAI_AEBActive_B;
    NVRAM_LDPSwitch_B = pLDPSAInput->NVRAM_LDPSwitch_B;
    NVRAM_LDPStartupSpd_Kmph = pLDPSAInput->NVRAM_LDPStartupSpd_Kmph;
    LDPSAI_VehStartupSpdHMI_Kmph = pLDPSAInput->LDPSAI_VehStartupSpdHMI_Kmph;

    /************************************LDPSA
     * function*************************************************************/
    LDPSA_step();

    /************************************LDPSA
     * output*************************************************************/
    pLDPSAOutput->LDPSC_DgrSide_St = LDPSC_DgrSide_St;
    pLDPSAOutput->LDPSC_RdyToTrig_B = LDPSC_RdyToTrig_B;
    pLDPSAOutput->LDPSC_SysOut_St = LDPSC_SysOut_St;
    pLDPSAOutput->LDPDT_LnPstnLf_Mi = LDPDT_LnPstnLf_Mi;
    pLDPSAOutput->LDPDT_LnPstnRi_Mi = LDPDT_LnPstnRi_Mi;
    pLDPSAOutput->LDPDT_LnHeadLf_Rad = LDPDT_LnHeadLf_Rad;
    pLDPSAOutput->LDPDT_LnHeadRi_Rad = LDPDT_LnHeadRi_Rad;
    pLDPSAOutput->LDPDT_LnCltdCurvLf_ReMi = LDPDT_LnCltdCurvLf_ReMi;
    pLDPSAOutput->LDPDT_LnCltdCurvRi_ReMi = LDPDT_LnCltdCurvRi_ReMi;
    pLDPSAOutput->LDPVSE_NVRAMVehStartupSpd_Kmph = LDPVSE_NVRAMVehStartupSpd_Kmph;
    pLDPSAOutput->LDPSC_NVRAMLDPSwitch_B = LDPSC_NVRAMLDPSwitch_B;

    /************************************LDPSA
     * debug*************************************************************/
    pLDPSADebug->LDPTT_LnBdryPstnXLf_Mi = LDPTT_LnBdryPstnXLf_Mi;
    pLDPSADebug->LDPTT_LnBdryPstnYLf_Mi = LDPTT_LnBdryPstnYLf_Mi;
    pLDPSADebug->LDPTT_LnBdryHeadAglLf_Rad = LDPTT_LnBdryHeadAglLf_Rad;
    pLDPSADebug->LDPTT_LnBdryCurvLf_ReMi = LDPTT_LnBdryCurvLf_ReMi;
    pLDPSADebug->LDPTT_LnBdryCurvRateLf_ReMi2 = LDPTT_LnBdryCurvRateLf_ReMi2;
    pLDPSADebug->LDPTT_LnBdryVldLengLf_Mi = LDPTT_LnBdryVldLengLf_Mi;
    pLDPSADebug->LDPTT_LnBdryPstnXRi_Mi = LDPTT_LnBdryPstnXRi_Mi;
    pLDPSADebug->LDPTT_LnBdryPstnYRi_Mi = LDPTT_LnBdryPstnYRi_Mi;
    pLDPSADebug->LDPTT_LnBdryHeadAglRi_Rad = LDPTT_LnBdryHeadAglRi_Rad;
    pLDPSADebug->LDPTT_LnBdryCurvRi_ReMi = LDPTT_LnBdryCurvRi_ReMi;
    pLDPSADebug->LDPTT_LnBdryCurvRateRi_ReMi2 = LDPTT_LnBdryCurvRateRi_ReMi2;
    pLDPSADebug->LDPTT_LnBdryVldLengRi_Mi = LDPTT_LnBdryVldLengRi_Mi;
    pLDPSADebug->LDPTT_LnBdryPstnXCent_Mi = LDPTT_LnBdryPstnXCent_Mi;
    pLDPSADebug->LDPTT_LnBdryPstnYCent_Mi = LDPTT_LnBdryPstnYCent_Mi;
    pLDPSADebug->LDPTT_LnBdryHeadAglCent_Rad = LDPTT_LnBdryHeadAglCent_Rad;
    pLDPSADebug->LDPTT_LnBdryCurvCent_ReMi = LDPTT_LnBdryCurvCent_ReMi;
    pLDPSADebug->LDPTT_LnBdryCurvRateCent_ReMi2 = LDPTT_LnBdryCurvRateCent_ReMi2;
    pLDPSADebug->LDPTT_LnBdryVldLengCent_Mi = LDPTT_LnBdryVldLengCent_Mi;
    pLDPSADebug->LDPTT_TgtPstnYLf_Mi = LDPTT_TgtPstnYLf_Mi;
    pLDPSADebug->LDPTT_TgtPstnYRi_Mi = LDPTT_TgtPstnYRi_Mi;
    pLDPSADebug->LDPTV_FTireAccMx_Mps2 = LDPTV_FTireAccMx_Mps2;
    pLDPSADebug->LDPTV_FTireAccMn_Mps2 = LDPTV_FTireAccMn_Mps2;
    pLDPSADebug->LDPTV_DstcYTgtAreaLf_Mi = LDPTV_DstcYTgtAreaLf_Mi;
    pLDPSADebug->LDPTV_DstcYTgtAreaRi_Mi = LDPTV_DstcYTgtAreaRi_Mi;
    pLDPSADebug->LDPTV_FctTgtDistY_Fct = LDPTV_FctTgtDistY_Fct;
    pLDPSADebug->LDPTV_TrajPlanServQu_Fct = LDPTV_TrajPlanServQu_Fct;
    pLDPSADebug->LDPTV_PredTiCurv_Sec = LDPTV_PredTiCurv_Sec;
    pLDPSADebug->LDPTV_PredTiAgl_Sec = LDPTV_PredTiAgl_Sec;
    pLDPSADebug->LDPTV_TiLmtEnDura_Sec = LDPTV_TiLmtEnDura_Sec;
    pLDPSADebug->LDPTV_JerkLmtMx_Mps3 = LDPTV_JerkLmtMx_Mps3;
    pLDPSADebug->LDPTV_VeloXObst_Mps = LDPTV_VeloXObst_Mps;
    pLDPSADebug->LDPTV_AccXObst_Mps2 = LDPTV_AccXObst_Mps2;
    pLDPSADebug->LDPTV_DstcXObst_Mi = LDPTV_DstcXObst_Mi;
    pLDPSADebug->LDPTV_DstcYObst_Mi = LDPTV_DstcYObst_Mi;
    pLDPSADebug->LDPTV_LmtCurvMx_ReMi = LDPTV_LmtCurvMx_ReMi;
    pLDPSADebug->LDPTV_LmtCurvGradIncMx_ReMps = LDPTV_LmtCurvGradIncMx_ReMps;
    pLDPSADebug->LDPTV_LmtCurvGradDecMx_ReMps = LDPTV_LmtCurvGradDecMx_ReMps;
    pLDPSADebug->LDPTV_SnsTiStamp_Sec = LDPTV_SnsTiStamp_Sec;
    pLDPSADebug->LDPTV_SteWhlGradLmt_Fct = LDPTV_SteWhlGradLmt_Fct;
    pLDPSADebug->LDPTV_SteWhlGrad_ReS = LDPTV_SteWhlGrad_ReS;
    pLDPSADebug->LDPTV_TrqRampGrad_ReS = LDPTV_TrqRampGrad_ReS;
    pLDPSADebug->LDPTV_MxTrqScalGradLmt_Fct = LDPTV_MxTrqScalGradLmt_Fct;
    pLDPSADebug->LDPTV_MxTrqScalGrad_ReS = LDPTV_MxTrqScalGrad_ReS;
    pLDPSADebug->LDPTV_WeightEndTi_Fct = LDPTV_WeightEndTi_Fct;
    pLDPSADebug->LDPTV_PlanningHorizon_Sec = LDPTV_PlanningHorizon_Sec;
    pLDPSADebug->LDPTV_DMCDeraLvl_Fct = LDPTV_DMCDeraLvl_Fct;
    pLDPSADebug->LDPTV_WidObst_Mi = LDPTV_WidObst_Mi;
    pLDPSADebug->LDPTV_LmtCurvGradCtrlMx_ReMps = LDPTV_LmtCurvGradCtrlMx_ReMps;
    pLDPSADebug->LDPSC_CrvSensiDecayRi_Mi = LDPSC_CrvSensiDecayRi_Mi;
    pLDPSADebug->LDPSC_DlcThdMode2_Mi = LDPSC_DlcThdMode2_Mi;
    pLDPSADebug->LDPSC_DlcThdMode3_Mi = LDPSC_DlcThdMode3_Mi;
    pLDPSADebug->LDPSC_DlcThdMode1_Mi = LDPSC_DlcThdMode1_Mi;
    pLDPSADebug->LDPSC_DstcToLnTrsd_Mi = LDPSC_DstcToLnTrsd_Mi;
    pLDPSADebug->LDPSC_DstcToLnTrsdCrvCpstnRi_Mi = LDPSC_DstcToLnTrsdCrvCpstnRi_Mi;
    pLDPSADebug->LDPSC_DstcToLnTrsdRi_Mi = LDPSC_DstcToLnTrsdRi_Mi;
    pLDPSADebug->LDPDT_CrvThdMaxRi_ReMi = LDPDT_CrvThdMaxRi_ReMi;
    pLDPSADebug->LDPDT_CrvThdHystRi_ReMi = LDPDT_CrvThdHystRi_ReMi;
    pLDPSADebug->LDPDT_RawDstcToLnRi_Mi = LDPDT_RawDstcToLnRi_Mi;
    pLDPSADebug->LDPDT_DstcToLnRi_Mi = LDPDT_DstcToLnRi_Mi;
    pLDPSADebug->LDPDT_RawLatVehSpdRi_Mps = LDPDT_RawLatVehSpdRi_Mps;
    pLDPSADebug->LDPDT_LatVehSpdRi_Mps = LDPDT_LatVehSpdRi_Mps;
    pLDPSADebug->LDPDT_TiToLnRi_Sec = LDPDT_TiToLnRi_Sec;
    pLDPSADebug->LDPSC_TiToLnTrsd_Sec = LDPSC_TiToLnTrsd_Sec;
    pLDPSADebug->LDPVSE_MaxLatVel_Mps = LDPVSE_MaxLatVel_Mps;
    pLDPSADebug->LDPDT_CrvThdMaxLf_ReMi = LDPDT_CrvThdMaxLf_ReMi;
    pLDPSADebug->LDPDT_CrvThdHystLf_ReMi = LDPDT_CrvThdHystLf_ReMi;
    pLDPSADebug->LDPDT_RawDstcToLnLf_Mi = LDPDT_RawDstcToLnLf_Mi;
    pLDPSADebug->LDPDT_DstcToLnLf_Mi = LDPDT_DstcToLnLf_Mi;
    pLDPSADebug->LDPSC_DstcToLnTrsdCrvCpstnLf_Mi = LDPSC_DstcToLnTrsdCrvCpstnLf_Mi;
    pLDPSADebug->LDPSC_CrvSensiDecayLe_Mi = LDPSC_CrvSensiDecayLe_Mi;
    pLDPSADebug->LDPSC_DstcToLnTrsdLf_Mi = LDPSC_DstcToLnTrsdLf_Mi;
    pLDPSADebug->LDPDT_RawLatVehSpdLf_Mps = LDPDT_RawLatVehSpdLf_Mps;
    pLDPSADebug->LDPDT_LatVehSpdLf_Mps = LDPDT_LatVehSpdLf_Mps;
    pLDPSADebug->LDPDT_TiToLnLf_Sec = LDPDT_TiToLnLf_Sec;
    pLDPSADebug->LDPVSE_MaxCrvBySpd_ReMi = LDPVSE_MaxCrvBySpd_ReMi;
    pLDPSADebug->LDPVSE_HystCrvBySpd_ReMi = LDPVSE_HystCrvBySpd_ReMi;
    pLDPSADebug->LDPSC_WRBlockTime_Sec = LDPSC_WRBlockTime_Sec;
    pLDPSADebug->LDPSC_RampoutTime_Sec = LDPSC_RampoutTime_Sec;
    pLDPSADebug->LDPTT_RawLnBdryPstnYLf_Mi = LDPTT_RawLnBdryPstnYLf_Mi;
    pLDPSADebug->LDPTT_RawLnBdryPstnYRi_Mi = LDPTT_RawLnBdryPstnYRi_Mi;
    pLDPSADebug->LDPTT_TgtLatDstcRi_Mi = LDPTT_TgtLatDstcRi_Mi;
    pLDPSADebug->LDPTT_TgtLatDstcLf_Mi = LDPTT_TgtLatDstcLf_Mi;
    pLDPSADebug->LDPTT_RawBdryPstnYCent_Mi = LDPTT_RawBdryPstnYCent_Mi;
    pLDPSADebug->LDPTV_LatVel_Mps = LDPTV_LatVel_Mps;
    pLDPSADebug->LDPSC_SuppValid_Debug = LDPSC_SuppValid_Debug;
    pLDPSADebug->LDPTV_TrajCtrlSt_St = LDPTV_TrajCtrlSt_St;
    pLDPSADebug->LDPDT_CurveTypeRi_St = LDPDT_CurveTypeRi_St;
    pLDPSADebug->LDPVSE_SidCdtnLDPRi_St = LDPVSE_SidCdtnLDPRi_St;
    pLDPSADebug->LDPDT_CurveTypeLe_St = LDPDT_CurveTypeLe_St;
    pLDPSADebug->LDPVSE_SidCdtnLDPLf_St = LDPVSE_SidCdtnLDPLf_St;
    pLDPSADebug->LDPVSE_IvldLDP_St = LDPVSE_IvldLDP_St;
    pLDPSADebug->LDPTV_HighStatReq_B = LDPTV_HighStatReq_B;
    pLDPSADebug->LDPTV_LatCpstnEn_B = LDPTV_LatCpstnEn_B;
    pLDPSADebug->LDPTV_LmtEn_B = LDPTV_LmtEn_B;
    pLDPSADebug->LDPTV_TrigReplan_B = LDPTV_TrigReplan_B;
    pLDPSADebug->LDPDT_RdyTrigLDP_B = LDPDT_RdyTrigLDP_B;
    pLDPSADebug->LDPDT_EnaSafety_B = LDPDT_EnaSafety_B;
    pLDPSADebug->LDPDT_EnaByInVldQlfrRi_B = LDPDT_EnaByInVldQlfrRi_B;
    pLDPSADebug->LDPDT_EnaByInVldQlfrSfRi_B = LDPDT_EnaByInVldQlfrSfRi_B;
    pLDPSADebug->LDPDT_LnTrigVldRi_B = LDPDT_LnTrigVldRi_B;
    pLDPSADebug->LDPDT_CclByInVldQlfrRi_B = LDPDT_CclByInVldQlfrRi_B;
    pLDPSADebug->LDPDT_LnCclVldRi_B = LDPDT_LnCclVldRi_B;
    pLDPSADebug->LDPDT_LnMakVldRi_B = LDPDT_LnMakVldRi_B;
    pLDPSADebug->LDPSC_RawTrigByDlcRi_B = LDPSC_RawTrigByDlcRi_B;
    pLDPSADebug->LDPSC_EnaTlcTrigRi_B = LDPSC_EnaTlcTrigRi_B;
    pLDPSADebug->LDPSC_RawTrigByTlcRi_B = LDPSC_RawTrigByTlcRi_B;
    pLDPSADebug->LDPSC_DlyTrigByTlcRi_B = LDPSC_DlyTrigByTlcRi_B;
    pLDPSADebug->LDPSC_EnaLdwTrigRi_B = LDPSC_EnaLdwTrigRi_B;
    pLDPSADebug->LDPSC_RstLdwTrigRi_B = LDPSC_RstLdwTrigRi_B;
    pLDPSADebug->LDPSC_HoldLdwTrigRi_B = LDPSC_HoldLdwTrigRi_B;
    pLDPSADebug->LDPSC_ResetForSafeRi_B = LDPSC_ResetForSafeRi_B;
    pLDPSADebug->LDPSC_SetForSafeRi_B = LDPSC_SetForSafeRi_B;
    pLDPSADebug->LDPVSE_EdgeRiseTurnSglRi_B = LDPVSE_EdgeRiseTurnSglRi_B;
    pLDPSADebug->LDPVSE_TrnSglRi_B = LDPVSE_TrnSglRi_B;
    pLDPSADebug->LDPVSE_RdyTrigLDW_B = LDPVSE_RdyTrigLDW_B;
    pLDPSADebug->LDPVSE_VehLatSpdVldRi_B = LDPVSE_VehLatSpdVldRi_B;
    pLDPSADebug->LDPSC_TrigBySideCondRi_B = LDPSC_TrigBySideCondRi_B;
    pLDPSADebug->LDPSC_TrigByPrjSpecRi_B = LDPSC_TrigByPrjSpecRi_B;
    pLDPSADebug->LDPSC_TrigRi_B = LDPSC_TrigRi_B;
    pLDPSADebug->LDPDT_EnaByCstruSiteLf_B = LDPDT_EnaByCstruSiteLf_B;
    pLDPSADebug->LDPDT_EnaByInVldQlfrLf_B = LDPDT_EnaByInVldQlfrLf_B;
    pLDPSADebug->LDPDT_EnaByInVldQlfrSfLf_B = LDPDT_EnaByInVldQlfrSfLf_B;
    pLDPSADebug->LDPDT_LnTrigVldLf_B = LDPDT_LnTrigVldLf_B;
    pLDPSADebug->LDPDT_CclByInVldQlfrLf_B = LDPDT_CclByInVldQlfrLf_B;
    pLDPSADebug->LDPDT_LnCclVldLf_B = LDPDT_LnCclVldLf_B;
    pLDPSADebug->LDPDT_LnMakVldLf_B = LDPDT_LnMakVldLf_B;
    pLDPSADebug->LDPSC_RawTrigByDlcLf_B = LDPSC_RawTrigByDlcLf_B;
    pLDPSADebug->LDPSC_EnaTlcTrigLf_B = LDPSC_EnaTlcTrigLf_B;
    pLDPSADebug->LDPSC_RawTrigByTlcLf_B = LDPSC_RawTrigByTlcLf_B;
    pLDPSADebug->LDPSC_DlyTrigByTlcLf_B = LDPSC_DlyTrigByTlcLf_B;
    pLDPSADebug->LDPSC_EnaLdwTrigLf_B = LDPSC_EnaLdwTrigLf_B;
    pLDPSADebug->LDPSC_RstLdwTrigLf_B = LDPSC_RstLdwTrigLf_B;
    pLDPSADebug->LDPSC_HoldLdwTrigLf_B = LDPSC_HoldLdwTrigLf_B;
    pLDPSADebug->LDPSC_ResetForSafeLf_B = LDPSC_ResetForSafeLf_B;
    pLDPSADebug->LDPSC_SetForSafeLf_B = LDPSC_SetForSafeLf_B;
    pLDPSADebug->LDPVSE_EdgeRiseTurnSglLf_B = LDPVSE_EdgeRiseTurnSglLf_B;
    pLDPSADebug->LDPVSE_TrnSglLf_B = LDPVSE_TrnSglLf_B;
    pLDPSADebug->LDPVSE_VehLatSpdVldLf_B = LDPVSE_VehLatSpdVldLf_B;
    pLDPSADebug->LDPSC_TrigBySideCondLf_B = LDPSC_TrigBySideCondLf_B;
    pLDPSADebug->LDPSC_TrigByPrjSpecLf_B = LDPSC_TrigByPrjSpecLf_B;
    pLDPSADebug->LDPSC_TrigLf_B = LDPSC_TrigLf_B;
    pLDPSADebug->LDPSC_Trig_B = LDPSC_Trig_B;
    pLDPSADebug->LDPSC_EnaDgrSide_B = LDPSC_EnaDgrSide_B;
    pLDPSADebug->LDPSC_FnsByDgrStLf_B = LDPSC_FnsByDgrStLf_B;
    pLDPSADebug->LDPSC_FnsByLatDistLf_B = LDPSC_FnsByLatDistLf_B;
    pLDPSADebug->LDPSC_FnsByHeadingLf_B = LDPSC_FnsByHeadingLf_B;
    pLDPSADebug->LDPSC_FnsByLatSpdLf_B = LDPSC_FnsByLatSpdLf_B;
    pLDPSADebug->LDPSC_DgrFnsLf_B = LDPSC_DgrFnsLf_B;
    pLDPSADebug->LDPSC_FnsByDgrStRi_B = LDPSC_FnsByDgrStRi_B;
    pLDPSADebug->LDPSC_FnsByLatDistRi_B = LDPSC_FnsByLatDistRi_B;
    pLDPSADebug->LDPSC_FnsByHeadingRi_B = LDPSC_FnsByHeadingRi_B;
    pLDPSADebug->LDPSC_FnsByLatSpdRi_B = LDPSC_FnsByLatSpdRi_B;
    pLDPSADebug->LDPSC_DgrFnsRi_B = LDPSC_DgrFnsRi_B;
    pLDPSADebug->LDPSC_MinLdwBySysSt_B = LDPSC_MinLdwBySysSt_B;
    pLDPSADebug->LDPSC_EdgeRiseForMinLdw_B = LDPSC_EdgeRiseForMinLdw_B;
    pLDPSADebug->LDPSC_HoldForMinLdw_B = LDPSC_HoldForMinLdw_B;
    pLDPSADebug->LDPSC_FlagMinTimeLDW_B = LDPSC_FlagMinTimeLDW_B;
    pLDPSADebug->LDPSC_DgrFns_B = LDPSC_DgrFns_B;
    pLDPSADebug->LDPSC_AbortBySpecific_B = LDPSC_AbortBySpecific_B;
    pLDPSADebug->LDPSC_AbortByVehSt_B = LDPSC_AbortByVehSt_B;
    pLDPSADebug->LDPSC_AbortByDrvSt_B = LDPSC_AbortByDrvSt_B;
    pLDPSADebug->LDPSC_AbortByCtrlSt_B = LDPSC_AbortByCtrlSt_B;
    pLDPSADebug->LDPSC_AbortBySysSt_B = LDPSC_AbortBySysSt_B;
    pLDPSADebug->LDPSC_AbortByAvlSt_B = LDPSC_AbortByAvlSt_B;
    pLDPSADebug->LDPSC_AbortByPrjSpec_B = LDPSC_AbortByPrjSpec_B;
    pLDPSADebug->LDPSC_Abort_B = LDPSC_Abort_B;
    pLDPSADebug->LDPSC_StrgRdy_B = LDPSC_StrgRdy_B;
    pLDPSADebug->LDPSC_SuppBySpecific_B = LDPSC_SuppBySpecific_B;
    pLDPSADebug->LDPSC_SuppByVehSt_B = LDPSC_SuppByVehSt_B;
    pLDPSADebug->LDPSC_SuppByDrvSt_B = LDPSC_SuppByDrvSt_B;
    pLDPSADebug->LDPSC_SuppByCtrlSt_B = LDPSC_SuppByCtrlSt_B;
    pLDPSADebug->LDPSC_SuppBySysSt_B = LDPSC_SuppBySysSt_B;
    pLDPSADebug->LDPSC_SuppyByAvlSt_B = LDPSC_SuppyByAvlSt_B;
    pLDPSADebug->LDPSC_SuppPrjSpec_B = LDPSC_SuppPrjSpec_B;
    pLDPSADebug->LDPSC_Suppresion_B = LDPSC_Suppresion_B;
    pLDPSADebug->LDPSC_WeakRdyBySpecific_B = LDPSC_WeakRdyBySpecific_B;
    pLDPSADebug->LDPSC_WeakRdyByVehSt_B = LDPSC_WeakRdyByVehSt_B;
    pLDPSADebug->LDPSC_WeakRdyByDrvSt_B = LDPSC_WeakRdyByDrvSt_B;
    pLDPSADebug->LDPSC_WeakRdyByCtrlSt_B = LDPSC_WeakRdyByCtrlSt_B;
    pLDPSADebug->LDPSC_WeakRdyBySysSt_B = LDPSC_WeakRdyBySysSt_B;
    pLDPSADebug->LDPSC_WeakRdyByAvlSt_B = LDPSC_WeakRdyByAvlSt_B;
    pLDPSADebug->LDPSC_WeakRdyByPrjSpec_B = LDPSC_WeakRdyByPrjSpec_B;
    pLDPSADebug->LDPSC_BlockTimeBySysOut_B = LDPSC_BlockTimeBySysOut_B;
    pLDPSADebug->LDPSC_RawBlockTimeByRampOut_B = LDPSC_RawBlockTimeByRampOut_B;
    pLDPSADebug->LDPSC_BlockTimeByRampOut_B = LDPSC_BlockTimeByRampOut_B;
    pLDPSADebug->LDPSC_BlockTime_B = LDPSC_BlockTime_B;
    pLDPSADebug->LDPSC_WkRdy_B = LDPSC_WkRdy_B;
    pLDPSADebug->LDPSC_CancelBySpecific_B = LDPSC_CancelBySpecific_B;
    pLDPSADebug->LDPSC_CancelByVehSt_B = LDPSC_CancelByVehSt_B;
    pLDPSADebug->LDPSC_CancelByDrvSt_B = LDPSC_CancelByDrvSt_B;
    pLDPSADebug->LDPSC_CancelByCtrlSt_B = LDPSC_CancelByCtrlSt_B;
    pLDPSADebug->LDPSC_CancelBySysSt_B = LDPSC_CancelBySysSt_B;
    pLDPSADebug->LDPSC_CancelByAvlSt_B = LDPSC_CancelByAvlSt_B;
    pLDPSADebug->LDPSC_CancelByPrjSpec_B = LDPSC_CancelByPrjSpec_B;
    pLDPSADebug->LDPSC_MaxDurationBySysSt_B = LDPSC_MaxDurationBySysSt_B;
    pLDPSADebug->LDPSC_EdgRiseForSysSt_B = LDPSC_EdgRiseForSysSt_B;
    pLDPSADebug->LDPSC_MaxDurationByStDly_B = LDPSC_MaxDurationByStDly_B;
    pLDPSADebug->LDPSC_TiWarmMx_B = LDPSC_TiWarmMx_B;
    pLDPSADebug->LDPSC_ErrSideByTrigLf_B = LDPSC_ErrSideByTrigLf_B;
    pLDPSADebug->LDPSC_ErrSideBySideCondLf_B = LDPSC_ErrSideBySideCondLf_B;
    pLDPSADebug->LDPSC_ErrSidByPrjSpecLf_B = LDPSC_ErrSidByPrjSpecLf_B;
    pLDPSADebug->LDPSC_ErrSidCdtnLf_B = LDPSC_ErrSidCdtnLf_B;
    pLDPSADebug->LDPSC_SideCondByDgrLf_B = LDPSC_SideCondByDgrLf_B;
    pLDPSADebug->LDPSC_CanelBySideLf_B = LDPSC_CanelBySideLf_B;
    pLDPSADebug->LDPSC_SideCondByDgrRi_B = LDPSC_SideCondByDgrRi_B;
    pLDPSADebug->LDPSC_ErrSideByTrigRi_B = LDPSC_ErrSideByTrigRi_B;
    pLDPSADebug->LDPSC_ErrSideBySideCondRi_B = LDPSC_ErrSideBySideCondRi_B;
    pLDPSADebug->LDPSC_ErrSidByPrjSpecRi_B = LDPSC_ErrSidByPrjSpecRi_B;
    pLDPSADebug->LDPSC_ErrSidCdtnRi_B = LDPSC_ErrSidCdtnRi_B;
    pLDPSADebug->LDPSC_CanelBySideRi_B = LDPSC_CanelBySideRi_B;
    pLDPSADebug->LDPSC_ErrSidCdtn_B = LDPSC_ErrSidCdtn_B;
    pLDPSADebug->LDPSC_CLatDevByDlcLf_B = LDPSC_CLatDevByDlcLf_B;
    pLDPSADebug->LDPSC_CLatDevByDgrLf_B = LDPSC_CLatDevByDgrLf_B;
    pLDPSADebug->LDPSC_CclLatDevLf_B = LDPSC_CclLatDevLf_B;
    pLDPSADebug->LDPSC_CLatDevByDlcRi_B = LDPSC_CLatDevByDlcRi_B;
    pLDPSADebug->LDPSC_CLatDevByDgrRi_B = LDPSC_CLatDevByDgrRi_B;
    pLDPSADebug->LDPSC_CclLatDevRi_B = LDPSC_CclLatDevRi_B;
    pLDPSADebug->LDPSC_CclLatDev_B = LDPSC_CclLatDev_B;
    pLDPSADebug->LDPSC_Cancel_B = LDPSC_Cancel_B;
    pLDPSADebug->LDPSC_Suppression_B = LDPSC_Suppression_B;
    pLDPSADebug->LDPVSE_TgtCntrByLnWidth_B = LDPVSE_TgtCntrByLnWidth_B;
    pLDPSADebug->LDPVSE_TgtCntrLnEn_B = LDPVSE_TgtCntrLnEn_B;
    pLDPSADebug->LDPTV_CurvInner_B = LDPTV_CurvInner_B;
    pLDPSADebug->LDPTV_CurvOuter_B = LDPTV_CurvOuter_B;
    pLDPSADebug->LDPSC_Degradation_B = LDPSC_Degradation_B;
    pLDPSADebug->LDPSC_DegradationEdgeRise_B = LDPSC_DegradationEdgeRise_B;
    pLDPSADebug->LDPSC_Degr_B = LDPSC_Degr_B;
    pLDPSADebug->LDPSC_DlyTiOfTiToLnRiMn_Sec = LDPSC_DlyTiOfTiToLnRiMn_Sec;
    pLDPSADebug->LDPSC_HdTiTrigRi_Sec = LDPSC_HdTiTrigRi_Sec;
    pLDPSADebug->LDPVSE_HodTiTrnSglRi_Sec = LDPVSE_HodTiTrnSglRi_Sec;
    pLDPSADebug->LDPSC_DlyTiOfTiToLnLfMn_Sec = LDPSC_DlyTiOfTiToLnLfMn_Sec;
    pLDPSADebug->LDPSC_HdTiTrigLf_Sec = LDPSC_HdTiTrigLf_Sec;
    pLDPSADebug->LDPVSE_HodTiTrnSglLf_Sec = LDPVSE_HodTiTrnSglLf_Sec;
    pLDPSADebug->LDPSC_HdTiWarming_Sec = LDPSC_HdTiWarming_Sec;
    pLDPSADebug->LDPSC_DlyTiTgtFns_Sec = LDPSC_DlyTiTgtFns_Sec;
    pLDPSADebug->LDPSC_HdTiFns_Sec = LDPSC_HdTiFns_Sec;
    pLDPSADebug->LDPSC_HdTiWarmMx_Sec = LDPSC_HdTiWarmMx_Sec;
    pLDPSADebug->LDPTT_LwLnBdryPstnXLf_Mi = LDPTT_LwLnBdryPstnXLf_Mi;
    pLDPSADebug->LDPTT_LstLnBdryPstnXLf_Mi = LDPTT_LstLnBdryPstnXLf_Mi;
    pLDPSADebug->LDPTT_LstLnBdryVldLengLf_Mi = LDPTT_LstLnBdryVldLengLf_Mi;
    pLDPSADebug->LDPTT_LwLnBdryVldLengLf_Mi = LDPTT_LwLnBdryVldLengLf_Mi;
    pLDPSADebug->LDPTT_LstLnBdryPstnYLf_Mi = LDPTT_LstLnBdryPstnYLf_Mi;
    pLDPSADebug->LDPTT_LstLnWidCalc_Mi = LDPTT_LstLnWidCalc_Mi;
    pLDPSADebug->LDPTT_LwLnBdryPstnYLf_Mi = LDPTT_LwLnBdryPstnYLf_Mi;
    pLDPSADebug->LDPTT_LwLnBdryPstnYRi_Mi = LDPTT_LwLnBdryPstnYRi_Mi;
    pLDPSADebug->LDPTT_LwLnBdryPstnXRi_Mi = LDPTT_LwLnBdryPstnXRi_Mi;
    pLDPSADebug->LDPTT_LwLnBdryHeadAglRi_Rad = LDPTT_LwLnBdryHeadAglRi_Rad;
    pLDPSADebug->LDPTT_LwLnBdryCurvRi_ReMi = LDPTT_LwLnBdryCurvRi_ReMi;
    pLDPSADebug->LDPTT_LwLnBdryCurvRateRi_ReMi2 = LDPTT_LwLnBdryCurvRateRi_ReMi2;
    pLDPSADebug->LDPTT_LwLnBdryVldLengRi_Mi = LDPTT_LwLnBdryVldLengRi_Mi;
    pLDPSADebug->LDPTT_LstTgtLatDstcRi_Mi = LDPTT_LstTgtLatDstcRi_Mi;
    pLDPSADebug->LDPTT_LstMxTgtLatDevRi_Mi = LDPTT_LstMxTgtLatDevRi_Mi;
    pLDPSADebug->LDPTT_LstTgtLatDevRi_Mi = LDPTT_LstTgtLatDevRi_Mi;
    pLDPSADebug->LDPTT_LstTgtLatDevLf_Mi = LDPTT_LstTgtLatDevLf_Mi;
    pLDPSADebug->LDPTT_LstTgtLatDstcLf_Mi = LDPTT_LstTgtLatDstcLf_Mi;
    pLDPSADebug->LDPTT_LstMxTgtLatDevLf_Mi = LDPTT_LstMxTgtLatDevLf_Mi;
    pLDPSADebug->LDPTT_LwLnBdryPstnYCent_Mi = LDPTT_LwLnBdryPstnYCent_Mi;
    pLDPSADebug->LDPTT_LstLnBdryPstnYCent_Mi = LDPTT_LstLnBdryPstnYCent_Mi;
    pLDPSADebug->LDPTT_LstLnBdryCurvCent_ReMi = LDPTT_LstLnBdryCurvCent_ReMi;
    pLDPSADebug->LDPTT_LwLnBdryCurvCent_ReMi = LDPTT_LwLnBdryCurvCent_ReMi;
    pLDPSADebug->LDPTV_LstPlanningHorizon_Sec = LDPTV_LstPlanningHorizon_Sec;
    pLDPSADebug->LDPTV_LstWeightEndTi_Fct = LDPTV_LstWeightEndTi_Fct;
    pLDPSADebug->LDPTT_LwLnBdryHeadAglCent_Rad = LDPTT_LwLnBdryHeadAglCent_Rad;
    pLDPSADebug->LDPTT_LstLnBdryHeadAglCent_Rad = LDPTT_LstLnBdryHeadAglCent_Rad;
    pLDPSADebug->LDPTT_LwLnBdryCurvRateCent_ReMi2 = LDPTT_LwLnBdryCurvRateCent_ReMi2;
    pLDPSADebug->LDPTT_LstLnBdryCurvRateCent_ReMi2 = LDPTT_LstLnBdryCurvRateCent_ReMi2;
    pLDPSADebug->LDPTT_LwLnBdryPstnXCent_Mi = LDPTT_LwLnBdryPstnXCent_Mi;
    pLDPSADebug->LDPTT_LstLnBdryPstnXCent_Mi = LDPTT_LstLnBdryPstnXCent_Mi;
    pLDPSADebug->LDPTT_LwLnBdryVldLengCent_Mi = LDPTT_LwLnBdryVldLengCent_Mi;
    pLDPSADebug->LDPTT_LstLnBdryVldLengCent_Mi = LDPTT_LstLnBdryVldLengCent_Mi;
    pLDPSADebug->LDPTV_LstSteWhlGrad_ReS = LDPTV_LstSteWhlGrad_ReS;
    pLDPSADebug->LDPTV_LstDMCDeraLvl_Fct = LDPTV_LstDMCDeraLvl_Fct;
    pLDPSADebug->LDPTT_LstLnBdryHeadAglLf_Rad = LDPTT_LstLnBdryHeadAglLf_Rad;
    pLDPSADebug->LDPTT_LwLnBdryHeadAglLf_Rad = LDPTT_LwLnBdryHeadAglLf_Rad;
    pLDPSADebug->LDPTT_LstLnBdryCurvLf_ReMi = LDPTT_LstLnBdryCurvLf_ReMi;
    pLDPSADebug->LDPTT_LwLnBdryCurvLf_ReMi = LDPTT_LwLnBdryCurvLf_ReMi;
    pLDPSADebug->LDPTT_LstLnBdryCurvRateLf_ReMi2 = LDPTT_LstLnBdryCurvRateLf_ReMi2;
    pLDPSADebug->LDPTT_LwLnBdryCurvRateLf_ReMi2 = LDPTT_LwLnBdryCurvRateLf_ReMi2;
    pLDPSADebug->LDPSC_HdTiDegr_Sec = LDPSC_HdTiDegr_Sec;
    pLDPSADebug->LDPSC_LstPrevDgrSide_St = LDPSC_LstPrevDgrSide_St;
    pLDPSADebug->LDPSC_DgrSideOld_St = LDPSC_DgrSideOld_St;
    pLDPSADebug->LDPDT_UHysCltdCurvVldRi_B = LDPDT_UHysCltdCurvVldRi_B;
    pLDPSADebug->LDPDT_BHysHeadAglTrigVldRi_B = LDPDT_BHysHeadAglTrigVldRi_B;
    pLDPSADebug->LDPDT_UHysHeadAglCclVldRi_B = LDPDT_UHysHeadAglCclVldRi_B;
    pLDPSADebug->LDPSC_HdTiTrigRiEn_B = LDPSC_HdTiTrigRiEn_B;
    pLDPSADebug->LDPSC_DisTrigRi_B = LDPSC_DisTrigRi_B;
    pLDPSADebug->LDPVSE_EdgeRisTrnSglLf_B = LDPVSE_EdgeRisTrnSglLf_B;
    pLDPSADebug->LDPVSE_BHysLatVehSpdVldRi_B = LDPVSE_BHysLatVehSpdVldRi_B;
    pLDPSADebug->LDPVSE_UHysLatVehSpdVldRi_B = LDPVSE_UHysLatVehSpdVldRi_B;
    pLDPSADebug->LDPDT_UHysCltdCurvVldLf_B = LDPDT_UHysCltdCurvVldLf_B;
    pLDPSADebug->LDPDT_BHysHeadAglTrigVldLf_B = LDPDT_BHysHeadAglTrigVldLf_B;
    pLDPSADebug->LDPDT_UHysHeadAglCclVldLf_B = LDPDT_UHysHeadAglCclVldLf_B;
    pLDPSADebug->LDPSC_HdTiTrigLfEn_B = LDPSC_HdTiTrigLfEn_B;
    pLDPSADebug->LDPSC_DisTrigLf_B = LDPSC_DisTrigLf_B;
    pLDPSADebug->LDPVSE_EdgeRisTrnSglRi_B = LDPVSE_EdgeRisTrnSglRi_B;
    pLDPSADebug->LDPVSE_BHysLatVehSpdVldLf_B = LDPVSE_BHysLatVehSpdVldLf_B;
    pLDPSADebug->LDPVSE_UHysLatVehSpdVldLf_B = LDPVSE_UHysLatVehSpdVldLf_B;
    pLDPSADebug->LDPSC_EdgeRisWarming_B = LDPSC_EdgeRisWarming_B;
    pLDPSADebug->LDPVSE_BHysSpdVeh_B = LDPVSE_BHysSpdVeh_B;
    pLDPSADebug->LDPVSE_UHysSteAgl_B = LDPVSE_UHysSteAgl_B;
    pLDPSADebug->LDPVSE_UHysSteAglSpd_B = LDPVSE_UHysSteAglSpd_B;
    pLDPSADebug->LDPVSE_BHysAccVehX_B = LDPVSE_BHysAccVehX_B;
    pLDPSADebug->LDPVSE_BHysAccVehY_B = LDPVSE_BHysAccVehY_B;
    pLDPSADebug->LDPVSE_UHysVehCurv_B = LDPVSE_UHysVehCurv_B;
    pLDPSADebug->LDPVSE_BHysLnWid_B = LDPVSE_BHysLnWid_B;
    pLDPSADebug->LDPSC_EdgeRisFns_B = LDPSC_EdgeRisFns_B;
    pLDPSADebug->LDPSC_EdgeRisWarmMx_B = LDPSC_EdgeRisWarmMx_B;
    pLDPSADebug->LDPTT_CtrlIniEn_B = LDPTT_CtrlIniEn_B;
    pLDPSADebug->LDPTT_LstControl_B = LDPTT_LstControl_B;
    pLDPSADebug->LDPTV_LstCtrl_St = LDPTV_LstCtrl_St;
    pLDPSADebug->LDPSC_EdgeRisDegr_B = LDPSC_EdgeRisDegr_B;
    pLDPSADebug->LDPSC_DegrOld_B = LDPSC_DegrOld_B;
    pLDPSADebug->LDPSC_SysOld_St = LDPSC_SysOld_St;
}
/* **********************************************************************
Autosar Memory Map
**************************************************************************** */
// #define DLMU2_STOP_CODE
// #include "Mem_Map.h" /* PRQA S 5087 */ /* MD_MSR_MemMap */